name: Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run verify
